import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  flex: { flex: 1 },
  scroll: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 28, paddingVertical: 48 },
  header: { marginBottom: 28, alignItems: 'center' },
  title: { fontSize: 32, fontWeight: '800', color: '#1a1a2e' },
  subtitle: { fontSize: 18, fontWeight: '700', color: '#1a1a2e', marginTop: 4 },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, fontSize: 14, color: '#333', paddingVertical: 0 },
  eyeBtn: { padding: 4 },
  mt14: { marginTop: 14 },
  mt12: { marginTop: 12 },
  forgotRow: { alignItems: 'center', marginTop: 14, marginBottom: 20 },
  forgotText: { color: '#4A90E2', fontWeight: '700', fontSize: 14 },
  loginBtn: {
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: 'center',
    backgroundColor: '#4A90E2',
  },
  loginBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  signupRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 16 },
  signupText: { color: '#888', fontSize: 14 },
  signupLink: { color: '#FFD700', fontSize: 14, fontWeight: '700' },
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#ddd' },
  dividerText: { marginHorizontal: 14, color: '#bbb', fontSize: 13, fontWeight: '600' },
  socialIcon: { marginRight: 10 },
  facebookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1877F2',
    borderRadius: 10,
    paddingVertical: 14,
  },
  facebookBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  googleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  googleBtnText: { color: '#333', fontSize: 15, fontWeight: '700' },
});
